### ISSUE TITLE
Add the open forum

### ISSUE THREAD

**Issue by digitaluniverse** [NDNUSeniorProj2020/ndnu-connect#33]

**Comment by digitaluniverse** [comment]
1. Create forum branch

**Comment by XZ7QN0** [comment]
How's this going? Haven't seen any updates on this.

**Comment by pv-gitjob** [comment]
Haven't heard anything about this in 3 weeks, and I don't see a branch for it. I went ahead and implemented part 2 and 3 from the example in Slack, https://simpleisbetterthancomplex.com/series/2017/09/11/a-complete-beginners-guide-to-django-part-2.html
