### ISSUE TITLE
Edit README

### ISSUE THREAD

**Issue by ChristianLapinig** [NDNUSeniorProj2020/ndnu-connect#34]
This would be really helpful for the frontend team to get the backend installed and running so we can play around with data. I know that when you first clone the project you have to create a virtualenv, install the dependencies, nuke and rebuild the database, but it would be nice to have something to show how to do get setup

**Comment by XZ7QN0** [comment]
Let me get something going and implemented in the `README` of the file. I'll go ahead and @ you once I have something going @ChristianLapinig, and I'll be sure to have you as the approver for the pull request.

**Comment by ChristianLapinig** [comment]
Thanks @XZ7QN0 !
