### ISSUE TITLE
Make display_name not a required field in User model

### ISSUE THREAD

**Issue by ChristianLapinig** [NDNUSeniorProj2020/ndnu-connect#66]
Ran into an issue on the frontend trying to register a user. It was working prior to the addition of the `display_name` field. Since the addition, users are not able to register because the `display_name` field is required when registering a user as seen in the error thrown below from Postman.
![Screen Shot 2020-04-08 at 4 24 10 PM](https://user-images.githubusercontent.com/11323135/78842638-693f0280-79b5-11ea-8304-2026b1bdc17c.png)

Is it possible to register users without making the `display_name` field required?

**Comment by pv-gitjob** [comment]
I just removed it completely since if we aren't going to have a display name when the user is being created, we won't be able to use it anywhere else without errors.
